apiVersion: v1
kind: Service
metadata: 
  name: couchbase-service
  labels: 
    app: couchbase-service-pod
spec: 
  ports:
    - port: 8091
  # label keys and values of the Pod started elsewhere
  selector: 
    app: couchbase-rc-pod

