apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pwx1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  flexVolume:
    driver: "px/flexvolume"
    fsType: "ext4"
    options:
      volumeID: "couchbase1"
      size: "1Gi"
      osdDriver: "pxd"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pwx2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  flexVolume:
    driver: "px/flexvolume"
    fsType: "ext4"
    options:
      volumeID: "couchbase2"
      size: "1Gi"
      osdDriver: "pxd"
